---
  task: flowvo
  global:
    modality:
      length: 1
    cacher:
      load_traj: false
    dataset:
      frame_skip: 0
      seq_stride: 1
      frame_dir: true
    parameter:
  data:
    1:
      file: "loader/data_cacher/data/mvsec_train_dataset.txt"
      modality: 
        mvsec_flow:
          "flow0":
            cacher_size: [260, 346]
            length: 2
          "mask0":
            cacher_size: [260, 346]
            length: 2
        mvsec_events:
          "events0":
            cacher_size: [15, 260, 346]
            length: 2
      cacher:
        # data_root_path_override: "/home/amigo/tmp/test_root"
        data_root_key: mvsec
        subset_framenum: 800
        worker_num: 3
      dataset:
        frame_skip: 0
      parameter:
        intrinsics: [640, 640, 320, 320, 320, 320]
        intrinsics_scale: [0.25, 0.25]